[project]
name = "scrapy_ra"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.9.2",
    "pandas>=2.2.3",
    "pyyaml>=6.0.2",
    "scrapy>=2.11.2",
    "seaborn>=0.13.2",
    "sqlmodel>=0.0.22",
]
