name: Update Database and Generate Plots

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:  

jobs:
  update-and-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install

      - name: Install the project dependencies
        run: uv sync 

      - name: Run Scrapy Spider to Update Database
        run: uv run scrapy crawl huggingface

      - name: Update README Run Counter
        run: |
          # Find the current count or default to 0 if not found
          count=$(grep -o 'This workflow has run [0-9]* times' README.md | grep -o '[0-9]*' || echo 0)
          new_count=$((count + 1))
          # Use `perl` to update the README with the new count
          perl -pe "s/This workflow has run $count times/This workflow has run $new_count times/" -i README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add huggingface_scraper.db plots/model_data_plot.png plots/dataset_data_plot.png
          git commit -m "Update database and plots" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
